name: delete branch on close pr (deprecated)

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated notice
        run: echo "Action deprecated
