name: Update PR from Issue Modification

on:
  issues:
    types:
      - edited

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: https://api.staging.allocator.tech
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Convert Issue To PR
        run: |
          RESPONSE=RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -X POST "${BACKEND_URL}/application/update-from-issu" \
          -H "Content-Type: application/json" \
          -d '{"issue_number": "'${{ github.event.issue.number }}'", "repo": "'$REPO_NAME'", "owner": "'${{ github.repository_owner }}'"}')

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Failed to convert issue to PR. HTTP response code: $RESPONSE"
            exit 1
          else
            echo "Issue successfully converted to PR."
          fi
