name: Update PR from Issue Modification

on:
  issues:
    types:
      - edited

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: https://api.staging.allocator.tech
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Convert Issue To PR
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo "Updating PR from Issue: ${{ github.event.issue.number }} in $REPO_NAME"

          # Make the curl request and capture the response code
          RESPONSE_CODE=$(curl -w "%{http_code}" -o /dev/null -s \
            --header "Content-Type: application/json" \
            --request POST \
            --data '{"issue_number": "'${{ github.event.issue.number }}'", "repo": "'$REPO_NAME'", "owner": "'${{ github.repository_owner }}'"}' \
            "${BACKEND_URL}/application/update-from-issu")

          echo "Response Code: $RESPONSE_CODE"

          if [ "$RESPONSE_CODE" -ne 200 ]; then
            echo "Failed to update PR from issue. Response code: $RESPONSE_CODE"
            exit 1
          fi