name: Update PR from Issue Modification

on:
  issues:
    types:
      - edited

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: localhost:8080
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Convert Issue To PR
        run: |
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" \
          --header "Content-Type: application/json" \
          --request POST \
          --data '{"issue_number": "'${{ github.event.issue.number }}'", "repo": "'$REPO_NAME'", "owner": "'${{ github.repository_owner }}'"}' \
          "${BACKEND_URL}/application/update-from-issue")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Failed to convert issue to PR. HTTP response code: $RESPONSE"
            exit 1
          else
            echo "Issue successfully converted to PR."
          fi
