name: Renew Cache

on:
  workflow_dispatch:
  schedule:
    # Schedule to run at 1 AM every day
    - cron: '0 1 * * *'

jobs:
  renew_cache:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: https://api.staging.allocator.tech
    steps:
      - name: Renew Application Cache
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -X POST "${BACKEND_URL}/application/cache/renewa" \
          -H "Content-Type: application/json" \
          -d '{"owner": "'${{ github.repository_owner }}'", "repo": "'$REPO_NAME'"}')

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Failed to renew cache. HTTP response code: $RESPONSE"
            exit 1
          else
            echo "$RESPONSE"
          fi